### ISSUE TITLE
Presentation of prompts and feedbacks (sequencing)

### ISSUE THREAD

**Issue by ghost** [philiprbrenan/SlipsAndSpills#22]
We need to think about the way that the app presents the initial prompts and associated feedbacks for each image. At the moment I don't think we get all the info about each photo until the learner has been playing for some time. While it's good that not all the info is given at once, it's still an issue because the 'feedbacks' (extra info about the photos) can come up later in the game for the first time and can appear/be presented as a prompt, so the user will not necessarily know that the prompt relates to the photo they have already seen. 
Am I right in thinking that prompts (i.e. titles of photos) are interchangeable with feedbacks (what I have written in as extra info about the photo)?

**Comment by ghost** [comment]
When I showed the app to the man from social services (re the prisons) he struggled to use the app because he was expecting to get a feedback after each time he selected the correct item but this doesn't happen - sometimes you just get the prompt again. Does this mean that when we write an app content we should always put the name of the image (the prompt) in front of the feedback?

**Comment by philiprbrenan** [comment]
(a) The game never questions the user about a fact that has not presented earlier in a situation where there was only one photo on the screen - so that the user had to chose the right answer and thus learn the fact.

(b) If the user gets a question wrong then their wrong choice is expanded and the correct information about that choice is displayed to reinforce the effect of (a). The user is  then given an opportunity to try again with the failing question.

(c) If the user gets the answer wrong three time in a row then the give up display is shown and their answer is corrected.

But on the whole that app avoids correcting the user: it just reiterating correct answers and tries to build on them.  When I was learning German I discovered that I responded poorly to people who corrected me and well to people who carried on regardless but with the correct German spoken slowly soon after a mistake so that I could make the connection/correction myself.

Thus the apps are almost always user positive and adjust to the user by focusing on the point of failure and repeating it frequently until the user makes the connection.  One can do this with a computer - a human teacher would get annoyed and thus become disliked and lose their effectiveness.. The app always tries to build positively on what you know to teach you more with infinite patience and good will.

**Comment by ghost** [comment]
I like the positive approach to correcting mistakes. 

The issue I’m having is that I think what is happening is that for example:
‘Two fall risks’ can come up when that feedback has never appeared as a feedback associated with its prompt and photo. So how would anyone ever know that ‘Two fall risks’ was associated with ‘long corridor poor lighting’ unless they had been taught that previously?

**Comment by philiprbrenan** [comment]
I believe that (a) above prevents this from happening.  But of course there might be a bug present that causes this not to happen - it will be difficult to find because of all the randomization that applied to the app to keep the user engaged.

**Comment by philiprbrenan** [comment]
Please make sure that when you do a demonstration that the app has been reset to the initial state it would have been  in just after download. If you have been playing an app for a while and then you give the app to some-one else to play they will get very confused because they will not know what the app is talking about.

**Comment by ghost** [comment]
Yes I have discovered that!
And the way to reset is only by uninstalling and reinstalling isn’t it?
