### ISSUE TITLE
The zoom thing definitely isn’t there in the same way as SMP

### ISSUE THREAD

**Issue by philiprbrenan** [philiprbrenan/SlipsAndSpills#34]
Please do the following:

Answer a question wrongly three times in a row (perhaps by constantly pushing the same wrong answer) and confirm that the right/wrong sequence is displayed on the third wrong answer?

**Comment by ghost** [comment]
Hi, SMP uses the zoomy thing in a different way. It zooms to highlight and teach the option in the beginning (first stage), which Falls doesn’t do. As I say, that might not be the end of the world.

The problem with Falls is that when it’s showing you you’ve made a mistake, it isn’t repeating the name/title of the image. It only repeats the thing you got wrong, which might be one of the feedbacks that the app has subsequently turned into a prompt.

So, for example, it picks up on ‘difficult to navigate’ (which is one of the feedbacks to ‘Dangerous bathroom' that has been converted to a prompt after first presenting it as a feedback), but it doesn’t also tell you ‘Obstacles’ first (i.e. the title/name of the image). This causes confusion because you don’t know if you’re correct or not.

Do we remedy this through code or through the way I write the content?

The way the music is being used is also causing confusion.

On the original Appa Apps the music started up when you went into race mode but this isn’t clear in Falls and the music just goes on and on and on (and some of it is very fraying on the nerves), with no indication as to why you are hearing it.

When it goes on and on I want to throw the phone out of the window - it’s that stressful!

Is there any way that a person could select their own music to play when they go into race mode?

How could a person do this without infringing copyright?

I’m about to look at 'playlist for life’ which is a way for people with dementia to create an iPod playlist - I don’t know if that’s of any use.


Jx

**Comment by philiprbrenan** [comment]
Moved to: #38
